import type { Word } from '@/types';

export const DAILY_WORDS: Word[] = [
  {
    id: 'daily-wisdom',
    word: 'Wisdom',
    definition: 'The capacity to make sound judgments and decisions by drawing on knowledge, experience, and deep understanding.',
    exampleSentence: 'She approached the conflict with wisdom, listening carefully before offering a measured response.',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-courage',
    word: 'Courage',
    definition: 'The ability to act rightly or pursue what matters despite fear, uncertainty, or significant personal risk.',
    exampleSentence: 'It took courage to stand up in the meeting and voice the concern everyone else had been thinking.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-gratitude',
    word: 'Gratitude',
    definition: 'A sincere appreciation for the good things in life, including the kindness of others and the circumstances that support your wellbeing.',
    exampleSentence: 'Writing down three things he was grateful for each morning gradually shifted his entire outlook.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-patience',
    word: 'Patience',
    definition: 'The ability to wait calmly through difficulty, delay, or provocation without becoming anxious or irritable.',
    exampleSentence: 'Learning a new language requires patience — progress is real even when it feels invisible.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-resilience',
    word: 'Resilience',
    definition: 'The capacity to recover from setbacks, adapt to adversity, and continue moving forward despite hardship.',
    exampleSentence: 'After losing the contract, the team\'s resilience showed in how quickly they regrouped and found a better opportunity.',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-clarity',
    word: 'Clarity',
    definition: 'The quality of being easy to understand or perceive, free from confusion, ambiguity, or mental fog.',
    exampleSentence: 'A long walk in the morning brought her the clarity she needed to finally make a decision.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-purpose',
    word: 'Purpose',
    definition: 'A deep sense of direction and meaning that guides how you spend your time and energy over the long term.',
    exampleSentence: 'He found his purpose not in a single career but in consistently showing up for the people around him.',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-growth',
    word: 'Growth',
    definition: 'The ongoing process of developing in capacity, understanding, or character, often through challenge and deliberate effort.',
    exampleSentence: 'The uncomfortable conversation turned out to be the most significant moment of growth in her year.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-balance',
    word: 'Balance',
    definition: 'A stable state achieved by giving appropriate weight and attention to competing demands, values, or areas of life.',
    exampleSentence: 'Finding balance doesn\'t mean doing everything equally — it means knowing when to prioritize and when to rest.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-trust',
    word: 'Trust',
    definition: 'A firm belief in the reliability, honesty, or ability of someone or something, built gradually through consistent action.',
    exampleSentence: 'Trust between the two colleagues grew slowly over months of following through on their commitments.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-creativity',
    word: 'Creativity',
    definition: 'The ability to generate original ideas, solutions, or expressions by connecting things in unexpected or imaginative ways.',
    exampleSentence: 'The best solution came not from the expert but from a junior team member whose creativity hadn\'t been constrained by convention.',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-empathy',
    word: 'Empathy',
    definition: 'The capacity to understand and share the feelings of another person, stepping beyond your own perspective into theirs.',
    exampleSentence: 'Her empathy made the patient feel heard in a way that a clinical diagnosis alone never could.',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-focus',
    word: 'Focus',
    definition: 'The deliberate concentration of attention and energy on a single task, goal, or idea to the exclusion of distractions.',
    exampleSentence: 'He turned off notifications and blocked two hours each morning — and that focus transformed his output.',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-integrity',
    word: 'Integrity',
    definition: 'The quality of being honest and having strong moral principles, acting consistently with your values even when no one is watching.',
    exampleSentence: 'Integrity showed in the small moments — returning the extra change, crediting the colleague, being honest about the mistake.',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-curiosity',
    word: 'Curiosity',
    definition: 'A strong desire to learn and understand, marked by a willingness to ask questions and explore the unfamiliar.',
    exampleSentence: 'Her curiosity about how things worked led her down a rabbit hole that eventually became her career.',
    category: 'daily',
    difficulty: 'beginner',
  },
];

export const PRACTICE_WORDS: Word[] = [
  {
    id: 'practice-hope',
    word: 'Hope',
    definition: 'An expectation or desire for a positive outcome, often sustaining effort and motivation through uncertainty.',
    exampleSentence: 'Hope is what kept him applying after every rejection — and eventually it was justified.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-change',
    word: 'Change',
    definition: 'The process of becoming different, whether through deliberate choice, external circumstance, or gradual evolution over time.',
    exampleSentence: 'The change she feared most turned out to be the one that opened the most doors.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-ambition',
    word: 'Ambition',
    definition: 'A strong desire to achieve something significant, often driving sustained effort and willingness to take risks.',
    exampleSentence: 'Her ambition was never about outpacing others — it was about exceeding what she believed was possible for herself.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-power',
    word: 'Power',
    definition: 'The capacity to influence outcomes, shape circumstances, or direct others, whether through authority, resources, or strength of character.',
    exampleSentence: 'Real power, he argued, is the ability to walk away from something without needing it.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-freedom',
    word: 'Freedom',
    definition: 'The condition of being able to act, speak, or think without external restraint, constraint, or coercion.',
    exampleSentence: 'She realized that financial freedom wasn\'t about having more — it was about needing less.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-truth',
    word: 'Truth',
    definition: 'That which accurately reflects reality or fact, as opposed to what is merely believed, convenient, or comforting.',
    exampleSentence: 'The hardest truths are usually the ones we already know but haven\'t been willing to say aloud.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-identity',
    word: 'Identity',
    definition: 'The set of qualities, values, beliefs, and characteristics that define who a person understands themselves to be.',
    exampleSentence: 'Leaving his hometown forced him to question which parts of his identity were truly his and which had simply been inherited.',
    category: 'practice',
    difficulty: 'advanced',
  },
  {
    id: 'practice-legacy',
    word: 'Legacy',
    definition: 'The lasting impact, memory, or influence a person leaves behind after they are gone or after a chapter ends.',
    exampleSentence: 'She wasn\'t building a legacy for her name — she was building one for the people who would benefit long after she\'d moved on.',
    category: 'practice',
    difficulty: 'advanced',
  },
  {
    id: 'practice-failure',
    word: 'Failure',
    definition: 'The experience of not achieving an intended outcome, often carrying lessons that success alone cannot teach.',
    exampleSentence: 'The failure stung for months, but looking back, it was the most clarifying event of her professional life.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-success',
    word: 'Success',
    definition: 'The achievement of a goal or desired outcome, though its meaning varies deeply depending on what a person values.',
    exampleSentence: 'He had achieved every marker of success he\'d been raised to pursue, and yet something still felt missing.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-simplicity',
    word: 'Simplicity',
    definition: 'The quality of being clear, uncomplicated, and free from unnecessary complexity, often requiring more discipline than complexity does.',
    exampleSentence: 'The best advice she ever received was two words — simplicity was harder to practice than any elaborate strategy.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-progress',
    word: 'Progress',
    definition: 'Forward movement toward a goal, improvement over time, or the gradual closing of the gap between where you are and where you want to be.',
    exampleSentence: 'Progress wasn\'t visible day to day, but the photographs from a year ago told a different story.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-doubt',
    word: 'Doubt',
    definition: 'A state of uncertainty or lack of conviction, which can paralyze but can also be a sign of honest, serious thinking.',
    exampleSentence: 'The doubt she felt before launching wasn\'t weakness — it was the part of her that wanted to get it right.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-belonging',
    word: 'Belonging',
    definition: 'The feeling of being accepted, valued, and genuinely included within a group, community, or relationship.',
    exampleSentence: 'She had lived in the city for years before she finally found a group that gave her a real sense of belonging.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-vision',
    word: 'Vision',
    definition: 'The ability to think about the future with imagination and wisdom, or a clear mental picture of a desired outcome.',
    exampleSentence: 'Without a vision for where the company was going, the team worked hard but in different directions.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-sacrifice',
    word: 'Sacrifice',
    definition: 'The act of giving up something valued in order to gain something more important or to serve a greater purpose.',
    exampleSentence: 'Every meaningful goal she had achieved required a sacrifice she hadn\'t fully understood when she made it.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-influence',
    word: 'Influence',
    definition: 'The capacity to affect the beliefs, behaviors, or decisions of others, often operating subtly through example or relationship.',
    exampleSentence: 'His influence on younger employees was most visible in the questions they started asking after working with him.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-choice',
    word: 'Choice',
    definition: 'The act of selecting between options, and the responsibility that comes with recognizing that your decisions shape your life.',
    exampleSentence: 'Every day is a series of small choices — and it\'s the accumulation of those choices that defines a life.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-fear',
    word: 'Fear',
    definition: 'An unpleasant emotion caused by the perception of danger or threat, real or imagined, which can either protect or constrain us.',
    exampleSentence: 'The fear of looking foolish had kept him from asking for help far longer than it should have.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-wonder',
    word: 'Wonder',
    definition: 'A feeling of awe, amazement, or admiration triggered by something beautiful, mysterious, or difficult to fully understand.',
    exampleSentence: 'Children move through the world with wonder that adults often have to consciously work to recover.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-solitude',
    word: 'Solitude',
    definition: 'Time spent alone, distinct from loneliness — often a deliberate choice that allows for reflection, restoration, and self-knowledge.',
    exampleSentence: 'She protected her Saturday mornings with fierce commitment, knowing that solitude was where she did her clearest thinking.',
    category: 'practice',
    difficulty: 'advanced',
  },
  {
    id: 'practice-momentum',
    word: 'Momentum',
    definition: 'The force or energy that builds when consistent action is taken over time, making continued progress increasingly easier.',
    exampleSentence: 'Once the project gained momentum, the obstacles that had seemed insurmountable began to dissolve on their own.',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-connection',
    word: 'Connection',
    definition: 'A meaningful relationship or bond between people, built through shared experience, honesty, and genuine mutual attention.',
    exampleSentence: 'The conference was full of networking, but real connection happened in the quiet conversation over coffee at the end.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-time',
    word: 'Time',
    definition: 'The irreversible progression of existence, and the finite resource whose allocation most clearly reflects what a person truly values.',
    exampleSentence: 'Looking back, she wished she had spent less time managing how she appeared and more time on what actually mattered.',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-perspective',
    word: 'Perspective',
    definition: 'A particular way of seeing and interpreting the world, shaped by experience, position, and the assumptions we bring to what we observe.',
    exampleSentence: 'Traveling alone for the first time gave him a perspective on his own life that no amount of reading had managed to provide.',
    category: 'practice',
    difficulty: 'intermediate',
  },
];

// getDailyWord returns a deterministic word based on the day of year
export function getDailyWord(): Word {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  return DAILY_WORDS[dayOfYear % DAILY_WORDS.length];
}

export function getRandomPracticeWord(excludeId?: string): Word {
  const available = excludeId
    ? PRACTICE_WORDS.filter((w) => w.id !== excludeId)
    : PRACTICE_WORDS;
  return available[Math.floor(Math.random() * available.length)];
}
