import type { Word } from '@/types';

export const DAILY_WORDS: Word[] = [
  {
    id: 'daily-wisdom',
    word: 'Wisdom',
    pronunciation: '/ˈwɪzdəm/',
    pos: 'noun',
    definition: 'The ability to make sound judgments from experience, knowledge, and good sense.',
    exampleSentence: '"She spoke with the wisdom of someone who had lived through great hardship."',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-courage',
    word: 'Courage',
    pronunciation: '/ˈkɜːrɪdʒ/',
    pos: 'noun',
    definition: 'The willingness to act despite fear, doing what is difficult or uncertain.',
    exampleSentence: '"It takes courage to admit when you are wrong."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-gratitude',
    word: 'Gratitude',
    pronunciation: '/ˈɡrætɪtjuːd/',
    pos: 'noun',
    definition: 'The recognition and appreciation of value received — a practice that shifts attention toward what already exists.',
    exampleSentence: '"A daily practice of gratitude changes what you notice."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-patience',
    word: 'Patience',
    pronunciation: '/ˈpeɪʃəns/',
    pos: 'noun',
    definition: 'The capacity to endure delay, difficulty, or discomfort without losing composure.',
    exampleSentence: '"Learning any skill requires patience and consistent effort."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-resilience',
    word: 'Resilience',
    pronunciation: '/rɪˈzɪliəns/',
    pos: 'noun',
    definition: 'The capacity to recover from setbacks, adapt to adversity, and continue moving forward despite hardship.',
    exampleSentence: '"After losing the contract, the team\'s resilience showed in how quickly they regrouped."',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-clarity',
    word: 'Clarity',
    pronunciation: '/ˈklærɪti/',
    pos: 'noun',
    definition: 'The quality of being coherent, precise, and free from ambiguity in thought or expression.',
    exampleSentence: '"When in doubt, wait for clarity before acting."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-purpose',
    word: 'Purpose',
    pronunciation: '/ˈpɜːrpəs/',
    pos: 'noun',
    definition: 'The underlying reason that gives meaning and direction to one\'s choices and effort.',
    exampleSentence: '"Without a sense of purpose, even success can feel hollow."',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-growth',
    word: 'Growth',
    pronunciation: '/ɡrəʊθ/',
    pos: 'noun',
    definition: 'A deliberate process of expanding one\'s capacity, skill, or understanding over time.',
    exampleSentence: '"Real growth rarely happens inside a comfort zone."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-balance',
    word: 'Balance',
    pronunciation: '/ˈbæləns/',
    pos: 'noun',
    definition: 'The dynamic state of maintaining equilibrium between competing forces, demands, or values.',
    exampleSentence: '"Balance is not a fixed state, but something you continuously return to."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-trust',
    word: 'Trust',
    pronunciation: '/trʌst/',
    pos: 'noun',
    definition: 'A firm belief in the reliability or truth of someone or something, earned through consistent action.',
    exampleSentence: '"Trust is built slowly and lost quickly."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-creativity',
    word: 'Creativity',
    pronunciation: '/ˌkriːeɪˈtɪvɪti/',
    pos: 'noun',
    definition: 'The ability to generate original ideas, solutions, or expressions by connecting things in unexpected ways.',
    exampleSentence: '"The best solution came not from the expert but from the junior team member whose creativity was unconstrained."',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-empathy',
    word: 'Empathy',
    pronunciation: '/ˈempəθi/',
    pos: 'noun',
    definition: 'The ability to understand and share the feelings of another from within their perspective.',
    exampleSentence: '"Empathy requires you to set aside your own perspective, however briefly."',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-focus',
    word: 'Focus',
    pronunciation: '/ˈfəʊkəs/',
    pos: 'noun',
    definition: 'The deliberate concentration of attention and energy on a single task or idea to the exclusion of distractions.',
    exampleSentence: '"He turned off notifications and blocked two hours each morning — and that focus transformed his output."',
    category: 'daily',
    difficulty: 'beginner',
  },
  {
    id: 'daily-integrity',
    word: 'Integrity',
    pronunciation: '/ɪnˈteɡrɪti/',
    pos: 'noun',
    definition: 'The quality of being honest and having strong moral principles, acting consistently with your values even when no one is watching.',
    exampleSentence: '"Integrity showed in the small moments — returning the extra change, crediting the colleague, being honest about the mistake."',
    category: 'daily',
    difficulty: 'intermediate',
  },
  {
    id: 'daily-curiosity',
    word: 'Curiosity',
    pronunciation: '/ˌkjʊərɪˈɒsɪti/',
    pos: 'noun',
    definition: 'An intrinsic drive to explore, question, and understand the world beyond what is already known.',
    exampleSentence: '"Curiosity is the engine of learning and the enemy of stagnation."',
    category: 'daily',
    difficulty: 'beginner',
  },
];

export const PRACTICE_WORDS: Word[] = [
  {
    id: 'practice-hope',
    word: 'Hope',
    pronunciation: '/həʊp/',
    pos: 'noun',
    definition: 'A forward-looking orientation that believes a better outcome is possible, even without certainty.',
    exampleSentence: '"Hope is not passive. It requires a belief that your actions matter."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-change',
    word: 'Change',
    pronunciation: '/tʃeɪndʒ/',
    pos: 'noun',
    definition: 'The process of becoming different — whether chosen, forced, or simply inevitable.',
    exampleSentence: '"Change is uncomfortable precisely because it asks something of you."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-ambition',
    word: 'Ambition',
    pronunciation: '/æmˈbɪʃən/',
    pos: 'noun',
    definition: 'A strong desire to achieve something significant, paired with the will to pursue it.',
    exampleSentence: '"Ambition without direction is energy without a destination."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-power',
    word: 'Power',
    pronunciation: '/ˈpaʊər/',
    pos: 'noun',
    definition: 'The capacity to act, influence, or bring about change — and the responsibility that comes with it.',
    exampleSentence: '"Power reveals character more reliably than hardship does."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-freedom',
    word: 'Freedom',
    pronunciation: '/ˈfriːdəm/',
    pos: 'noun',
    definition: 'The condition of acting without external constraint while bearing responsibility for those actions.',
    exampleSentence: '"True freedom is inseparable from the responsibility it demands."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-truth',
    word: 'Truth',
    pronunciation: '/truːθ/',
    pos: 'noun',
    definition: 'That which accurately reflects reality or fact, as opposed to what is merely believed, convenient, or comforting.',
    exampleSentence: '"The hardest truths are usually the ones we already know but haven\'t been willing to say aloud."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-identity',
    word: 'Identity',
    pronunciation: '/aɪˈdentɪti/',
    pos: 'noun',
    definition: 'The set of qualities, beliefs, and experiences that define who a person understands themselves to be.',
    exampleSentence: '"Identity is less what you are born with and more what you choose to become."',
    category: 'practice',
    difficulty: 'advanced',
  },
  {
    id: 'practice-legacy',
    word: 'Legacy',
    pronunciation: '/ˈleɡəsi/',
    pos: 'noun',
    definition: 'The lasting impact a person\'s choices leave on others long after the moment has passed.',
    exampleSentence: '"A legacy is not built in a single moment, but across thousands of small choices."',
    category: 'practice',
    difficulty: 'advanced',
  },
  {
    id: 'practice-failure',
    word: 'Failure',
    pronunciation: '/ˈfeɪljər/',
    pos: 'noun',
    definition: 'An outcome that falls short of intention, and the primary source of durable learning.',
    exampleSentence: '"Every significant failure carries a lesson worth the cost."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-success',
    word: 'Success',
    pronunciation: '/səkˈses/',
    pos: 'noun',
    definition: 'The achievement of a goal or desired outcome, though its meaning varies deeply depending on what a person values.',
    exampleSentence: '"He had achieved every marker of success he\'d been raised to pursue, and yet something still felt missing."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-simplicity',
    word: 'Simplicity',
    pronunciation: '/sɪmˈplɪsɪti/',
    pos: 'noun',
    definition: 'The quality of being clear, uncomplicated, and free from unnecessary complexity, often requiring more discipline than complexity does.',
    exampleSentence: '"Simplicity was harder to practice than any elaborate strategy."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-progress',
    word: 'Progress',
    pronunciation: '/ˈprəʊɡres/',
    pos: 'noun',
    definition: 'Forward movement toward a goal, improvement over time, or the gradual closing of the gap between where you are and where you want to be.',
    exampleSentence: '"Progress wasn\'t visible day to day, but the photographs from a year ago told a different story."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-doubt',
    word: 'Doubt',
    pronunciation: '/daʊt/',
    pos: 'noun',
    definition: 'A state of uncertainty or lack of conviction, which can paralyze but can also be a sign of honest, serious thinking.',
    exampleSentence: '"The doubt she felt before launching wasn\'t weakness — it was the part of her that wanted to get it right."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-belonging',
    word: 'Belonging',
    pronunciation: '/bɪˈlɒŋɪŋ/',
    pos: 'noun',
    definition: 'The feeling of being accepted, valued, and genuinely included within a group, community, or relationship.',
    exampleSentence: '"She had lived in the city for years before she finally found a group that gave her a real sense of belonging."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-vision',
    word: 'Vision',
    pronunciation: '/ˈvɪʒən/',
    pos: 'noun',
    definition: 'The ability to think about the future with imagination and wisdom, or a clear mental picture of a desired outcome.',
    exampleSentence: '"Without a vision for where the company was going, the team worked hard but in different directions."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-sacrifice',
    word: 'Sacrifice',
    pronunciation: '/ˈsækrɪfaɪs/',
    pos: 'noun',
    definition: 'The act of giving up something valued in order to gain something more important or to serve a greater purpose.',
    exampleSentence: '"Every meaningful goal she had achieved required a sacrifice she hadn\'t fully understood when she made it."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-influence',
    word: 'Influence',
    pronunciation: '/ˈɪnfluəns/',
    pos: 'noun',
    definition: 'The capacity to affect the beliefs, behaviors, or decisions of others, often operating subtly through example or relationship.',
    exampleSentence: '"His influence on younger employees was most visible in the questions they started asking after working with him."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-choice',
    word: 'Choice',
    pronunciation: '/tʃɔɪs/',
    pos: 'noun',
    definition: 'The act of selecting between options, and the responsibility that comes with recognizing that your decisions shape your life.',
    exampleSentence: '"Every day is a series of small choices — and the accumulation of those choices defines a life."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-fear',
    word: 'Fear',
    pronunciation: '/fɪər/',
    pos: 'noun',
    definition: 'An instinctive response to perceived threat that shapes behavior, often below conscious awareness.',
    exampleSentence: '"Fear is most powerful when left unexamined."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-wonder',
    word: 'Wonder',
    pronunciation: '/ˈwʌndər/',
    pos: 'noun',
    definition: 'A feeling of awe, amazement, or admiration triggered by something beautiful, mysterious, or difficult to fully understand.',
    exampleSentence: '"Children move through the world with wonder that adults often have to consciously work to recover."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-solitude',
    word: 'Solitude',
    pronunciation: '/ˈsɒlɪtjuːd/',
    pos: 'noun',
    definition: 'Time spent alone, distinct from loneliness. Often a deliberate choice that allows for reflection, restoration, and self-knowledge.',
    exampleSentence: '"In solitude, the mind finds room to hear itself."',
    category: 'practice',
    difficulty: 'advanced',
  },
  {
    id: 'practice-momentum',
    word: 'Momentum',
    pronunciation: '/məˈmentəm/',
    pos: 'noun',
    definition: 'The force or energy that builds when consistent action is taken over time, making continued progress increasingly easier.',
    exampleSentence: '"Once the project gained momentum, the obstacles that had seemed insurmountable began to dissolve on their own."',
    category: 'practice',
    difficulty: 'intermediate',
  },
  {
    id: 'practice-connection',
    word: 'Connection',
    pronunciation: '/kəˈnekʃən/',
    pos: 'noun',
    definition: 'A meaningful relationship or bond between people, built through shared experience, honesty, and genuine mutual attention.',
    exampleSentence: '"Real connection happened in the quiet conversation over coffee at the end."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-time',
    word: 'Time',
    pronunciation: '/taɪm/',
    pos: 'noun',
    definition: 'The irreversible progression of existence in which all experience occurs — the only truly finite resource.',
    exampleSentence: '"Time spent in alignment with your values is rarely time wasted."',
    category: 'practice',
    difficulty: 'beginner',
  },
  {
    id: 'practice-perspective',
    word: 'Perspective',
    pronunciation: '/pəˈspektɪv/',
    pos: 'noun',
    definition: 'A particular way of seeing and interpreting the world, shaped by experience, position, and the assumptions we bring to what we observe.',
    exampleSentence: '"Traveling alone for the first time gave him a perspective on his own life that no amount of reading had managed to provide."',
    category: 'practice',
    difficulty: 'intermediate',
  },
];

// getDailyWord returns a deterministic word based on the day of year
export function getDailyWord(): Word {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  return DAILY_WORDS[dayOfYear % DAILY_WORDS.length];
}

export function getRandomPracticeWord(excludeId?: string): Word {
  const available = excludeId
    ? PRACTICE_WORDS.filter((w) => w.id !== excludeId)
    : PRACTICE_WORDS;
  return available[Math.floor(Math.random() * available.length)];
}
